"""Exchange client interface contract.

Both the MEXC client (bot/exchange/client.py) and the Binance client
(bot/exchange/binance_client.py) implement this surface. Engines, services and
handlers depend only on these method names and return shapes, never on a
specific exchange.

Return-shape contract (the important ones):

- get_positions() -> list[dict], each:
    {symbol, side("long"|"short"), contracts(float), entry_price, mark_price,
     liquidation_price, unrealized_pnl, margin, leverage(int), percentage,
     margin_mode("cross"|"isolated"), position_id}
- get_futures_balance() -> {free:{USDT}, total:{USDT}, used:{USDT},
     USDT:{free,total,used}, _raw:{availableOpen,...}}
- place_futures_order(...) -> {id, symbol, side("buy"|"sell"), amount(contracts),
     price, leverage, margin_mode, info}
- get_tp_sl_orders(symbol=None) -> list[dict], each:
    {id, symbol, trigger_price(float), side(int close-side), trigger_type(int),
     state} where trigger_type for long: TP=1/SL=2, for short: TP=2/SL=1.
- set_tp_sl(...) -> list[dict] of {type:"TP"|"SL"|"skip", price?, result:{success,...}}
- was_closed_by_tp(symbol, pos_side, opened_at_ms=None) -> (bool|None, float|None)
- get_funding_rate(symbol) -> {rate, next_funding_time, symbol}
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class IExchangeClient(Protocol):
    def futures_symbol(self, symbol: str) -> str: ...
    async def close(self) -> None: ...

    async def get_futures_balance(self) -> dict: ...
    async def get_spot_balance(self) -> dict: ...
    async def get_free_futures_balance(self) -> float: ...
    async def transfer_usdt(self, amount: float, direction: str) -> None: ...

    async def get_ticker(self, symbol: str) -> dict: ...
    async def get_ohlcv(self, symbol: str, timeframe: str = "1h", limit: int = 100) -> list: ...
    async def get_funding_rate(self, symbol: str) -> dict: ...
    async def get_contract_details(self) -> list: ...
    async def get_max_leverage(self, symbol: str) -> int: ...
    async def get_min_order_usdt(self, symbol: str, leverage: int) -> float: ...
    async def get_position_limit_usdt(self, symbol: str, leverage: int) -> float: ...

    async def get_positions(self) -> list[dict]: ...
    async def get_position(self, symbol: str) -> dict | None: ...
    async def set_leverage(self, symbol: str, leverage: int, side: str = "buy",
                           open_type: int = 2) -> dict: ...
    async def place_futures_order(self, symbol: str, side: str, amount_usdt: float,
                                  leverage: int, margin_mode: str | None = None) -> dict: ...
    async def partial_close_futures_position(self, symbol: str, contracts) -> dict: ...
    async def close_futures_position(self, symbol: str) -> dict: ...

    async def set_tp_sl(self, symbol: str, tp_price: float | None = None,
                        sl_price: float | None = None, pos_data: dict | None = None,
                        sl_limit_price: float | None = None) -> list[dict]: ...
    async def get_tp_sl_orders(self, symbol: str | None = None) -> list[dict]: ...
    async def cancel_tp_sl_orders(self, symbol: str) -> int: ...
    async def cancel_plan_orders(self, symbol: str) -> None: ...
    async def get_limit_close_orders(self, symbol: str) -> list[dict]: ...
    async def was_closed_by_tp(self, symbol: str, pos_side: str,
                               opened_at_ms: int | None = None): ...
